# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_success:
    - Rscript -e 'covr::codecov()'
    - R CMD BiocCheck .

r:
    - bioc-devel

notifications: # To avoid filling the inbox
  email:
    on_success: change
    on_failure: change
